project:
  type: website
  output-dir: docs

website:
  title: "BioMolic"
  open-graph:
    image: Images/avatar.png
    image-alt: "Iceland logo"
  navbar:
    logo: Images/avatar.png
    right:
      - href: index.qmd
        icon: house-door-fill
        text: " "
      - href: about.qmd
        text: About me
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
      - icon: github
        href: https://github.com/mgomezv26
      - icon: linkedin
        href: https://www.linkedin.com/in/monicagomezvadillo/
      - icon: twitter
        href: https://x.com/BioMolic


format:
  html:
    theme:
      light: flatly
      dark: darkly
    toggle: true


